# -*- coding: utf-8 -*-
"""Compnany banktruptcy predictio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pq9XpBi_I_TMsBTSnBm8RQTd9R1_dhV
"""

#importing libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#importing dataset
df = pd.read_csv('/content/drive/MyDrive/bankruptcy.csv')

df.head()

df.shape

df.info()

df['Bankrupt?'].value_counts()

df.isnull().sum()

sns.countplot(x='Bankrupt?', data=df)

#defining dependent and independent variables
x = df.drop('Bankrupt?', axis=1)
y = df['Bankrupt?']

#splitting data into training and testing set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

#training model
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter = 10000)
lr.fit(x_train,y_train)

#getting confusion matrix
from sklearn.metrics import confusion_matrix,classification_report
y_pred = lr.predict(x_test)
#checking accuracy
from sklearn.metrics import accuracy_score
lra = accuracy_score(y_test,y_pred)
print('accuracy score = ',lra)